repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.9.5
    hooks:
      # Linter.
      - id: ruff
        args: ["--fix", "--show-fixes"]
      # Formatter.
      - id: ruff-format

  - repo: https://github.com/rbubley/mirrors-prettier
    rev: v3.4.2
    hooks:
      - id: prettier
        exclude: static_redirector/templates/
